name: techgrains
description: Developer friendly app library having various commonly used functionality.
version: 1.1.3
homepage: https://github.com/techgrains/TGFramework-Flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.1"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  yaml: ^2.2.1
  shared_preferences: ^0.5.7+3
  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

